apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: order-svc
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: order-svc
spec:
  params:
  - name: ports
    value:
    - containerPort: 6000
      name: app
      port: 6000
  env:
  - name: ORDER_DB_HOST
    value: order-postgres
  - name: ORDER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: order-postgres-pass
        key: password
  - name: ORDER_DB_PORT
    value: "5432"
  - name: AUTH_MODE
    value: "1"
  - name: ORDER_DB_USERNAME
    value: pgbench
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: order-postgres-pass
        key: password
  - name: ORDER_AUTH_DB
    value: postgres
  - name: ORDER_PORT
    value: "6000"
  - name: PAYMENT_PORT
    value: "9000"
  - name: PAYMENT_HOST
    value: payment
  - name: USER_HOST
    value: users
  - name: USER_PORT
    value: "8083"
  image: harbor.mgt.mytanzu.org/acme/build/order:v0.1