apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: user-svc
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: user-svc
spec:
  params:
  - name: ports
    value:
    - containerPort: 8083
      name: app
      port: 8083
  env:
  - name: USERS_DB_HOST
    value: users-mongo
  - name: USERS_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: users-mongo-pass
        key: password
  - name: USERS_DB_PORT
    value: "27017"
  - name: USERS_DB_USERNAME
    value: mongoadmin
  - name: USERS_PORT
    value: "8083"
  - name: REDIS_HOST
    value: users-redis
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: users-redis-pass
        key: password
  image: harbor.mgt.mytanzu.org/acme/build/user:v0.1