apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cart-svc
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: cart-svc
spec:
  params:
  - name: ports
    value:
    - containerPort: 5000
      name: app
      port: 5000
  env:
  - name: REDIS_HOST
    value: cart-redis
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cart-redis-pass
        key: password
  - name: REDIS_PORT
    value: "6379"
  - name: CART_PORT
    value: "5000"
  - name: USER_HOST
    value: users
  - name: USER_PORT
    value: "8083"
  - name: AUTH_MODE
    value: "1"
  image: harbor.mgt.mytanzu.org/acme/build/cart:v0.1